---
- name: Generate secrets and configs using once off container
  docker_container:
    name: ceph_mon
    image: ceph/daemon:{{ ceph_version }}
    network_mode: host
    state: started
    volumes:
      - '{{ root_out_destination }}/ceph/etc:/etc/ceph'
      - '{{ root_out_destination }}/ceph/var:/var/lib/ceph'
    env:
      MON_IP: "{{ ipv4_address }}"
      CEPH_PUBLIC_NETWORK: "{{ ipv4_netmask | ipaddr('net') }}"
      DEBUG: 'verbose'
    command: mon

- name: Output map to file on host
  command: docker exec ceph_mon ceph mon getmap -o /etc/ceph/ceph.monmap

- name: Output auth credentials for OSDs
  command: docker exec ceph_mon ceph auth get client.bootstrap-osd -o /var/lib/ceph/bootstrap-osd/ceph.keyring

- name: Remove once off container
  docker_container:
    name: ceph_mon
    state: absent

- name: Register all Swarm configs
  command: docker config ls -q
  register: swarm_configs

- name: Delete all Swarm configs
  command: docker config rm {{ item }}
  with_items: "{{ swarm_configs.stdout_lines }}"
  when: swarm_configs.stdout_lines != []

- name: Register all Swarm secrets
  command: docker secret ls -q
  register: swarm_secrets

- name: Delete all Swarm secrets
  command: docker secret rm {{ item }}
  with_items: "{{ swarm_secrets.stdout_lines }}"
  when: swarm_secrets.stdout_lines != []

- name: Create ceph.conf config from file
  command: docker config create ceph.conf '{{ root_out_destination }}/ceph/etc/ceph.conf'

- name: Create ceph.monmap secret from file
  command: docker secret create ceph.monmap '{{ root_out_destination }}/ceph/etc/ceph.monmap'

- name: Create ceph.client.admin.keyring secret from file
  command: docker secret create ceph.client.admin.keyring '{{ root_out_destination }}/ceph/etc/ceph.client.admin.keyring'

- name: Create ceph.mon.keyring secret from file
  command: docker secret create ceph.mon.keyring '{{ root_out_destination }}/ceph/etc/ceph.mon.keyring'

- name: Create ceph.bootstrap-osd.keyring secret from file
  command: docker secret create ceph.bootstrap-osd.keyring '{{ root_out_destination }}/ceph/var/bootstrap-osd/ceph.keyring'