---
- name: Write out docker-compose-storage.yml template
  template:
    src: docker-compose-storage.yml.j2
    dest: '{{ root_out_destination }}/docker-compose-storage.yml'

- name: Deploy storage stack to swarm
  command: docker stack deploy --with-registry-auth --compose-file {{ root_out_destination }}/docker-compose-storage.yml storage
