---
- name: Write out docker-compose-storage.yml template
  template:
    src: docker-compose-storage.yml.j2
    dest: '{{ root_out_destination }}/docker-compose-storage.yml'

- name: Deploy storage stack from compose file
  docker_stack:
    state: present
    name: storage
    compose:
      - "{{ root_out_destination }}/docker-compose-storage.yml"
    with_registry_auth: yes