---
- import_tasks: setup-all.yml

- import_tasks: setup.yml
  when: ansible_hostname == groups['docker_swarm_manager'][0]

- import_tasks: cleanup.yml
  when: ansible_hostname == groups['docker_swarm_manager'][0]

- import_tasks: configs-and-secrets.yml
  when: ansible_hostname == groups['docker_swarm_manager'][0]

- import_tasks: deploy.yml
  when: ansible_hostname == groups['docker_swarm_manager'][0]

- import_tasks: configure.yml
  when: ansible_hostname == groups['docker_swarm_manager'][0]

- import_tasks: modules.yml
  when: ansible_hostname == groups['docker_swarm_manager'][0]

- import_tasks: prepare.yml

- import_tasks: authorise.yml

- import_tasks: mount.yml