---
- hosts: all
  become: true
  tasks:
    - name: Create OSD directory
      file:
        path: /mnt/osd
        state: directory
        recurse: yes

- hosts: docker_swarm_manager[0]
  become: true
  vars_files:
    - vaults/vault.yml
  roles:
    - deploy-storage

- hosts: all
  become: true
  roles:
    - mount-storage
